start of tile generation automation

diff --git a/bedrock-manage b/bedrock-manage
--- a/bedrock-manage
+++ b/bedrock-manage
@@ -1,19 +1,29 @@
 #!/bin/bash
 
-# User Settings
+# User-Editable Settings
 mc_dir="/home/clockfort/minecraft"
 mc_screen_name="minecraft_server"
+mc_world_name="morr"
 mc_logfile="$mc_dir/minecraft.log"
 mc_shutdown_timeout="15s"
 mc_backups_dir="/home/clockfort/minecraft_backups"
 
+mc_generate_maps="false"
+mc_force_regenerate_maps="true"
+www_dir="/var/www/html"
+unmined_dir="/home/clockfort/unmined"
+
+
+# Computed Parameters
 cd "$mc_dir"
 mkdir -p $mc_backups_dir
 
 mc_pid=`pidof bedrock_server`
 mc_ret=$?
-mc_backup_name=`date +'mc_backup_%Y_%m_%d_%H_%M_%S'`
 
+timestamp_iso8601=`date --iso-8601`
+mc_backup_name=`date +'mc_backup_%Y_%m_%d_%H_%M_%S'`
+backup_fullpath="$mc_backups_dir/mc_backup_name"
 
 start_mc_server () {
 	echo "Starting minecraft server. Logs will be written to $mc_logfile"
@@ -29,7 +39,6 @@ start_mc_server () {
 }
 
 backup_offline () {
-	local backup_fullpath="$mc_backups_dir/$mc_backup_name"
 	local tar_fullpath="$mc_backups_dir/$mc_backup_name.tar.gz"
 
 	echo "Performing an offline backup to $backup_fullpath ..."
@@ -39,6 +48,9 @@ backup_offline () {
 	echo "Compressing..."
 	cd "$mc_backups_dir"
 	time tar czf "$mc_backup_name.tar.gz" --exclude='bedrock_server' --exclude='bedrock_server_symbols.debug' "$mc_backup_name"
+	if [ $mc_generate_maps = "true" ]; then
+		generate_maps
+	fi
 	rm -fr "$mc_backup_name"
 	cd "$mc_dir"
 
@@ -81,6 +93,43 @@ stop_running_server () {
 		echo "Detected a clean shutdown and flush of the server."
 	else
 		echo "Error: Did not detect a clean shutdown and flush of the server. Please consult $mc_logfile for more information."
+		exit 1
+	fi
+}
+
+generate_maps () {
+	if [ $mc_force_regenerate_maps = "true" ]; then
+		echo "Removing existing maps data..."
+		rm -r "$www_dir/overworld"
+		rm -r "$www_dir/nether"
+		rm -r "$www_dir/nether_lower"
+	fi
+
+	local pid_list=""
+	local max_err=0
+
+	echo "Generating overworld map..."
+	time "$unmined_dir/unmined-cli" web render --world="$backup_fullpath/worlds/$mc_world_name" --output="$www_dir/overworld" \
+		--zoomout=4 --zoomin=4 --dimension overworld --background="#000000" -f --log-level="warning" &
+	pid_list="$pid_list $!"
+
+	echo "Generasting nether map [upper slice]..."
+	"$unmined_dir/unmined-cli" web render --world="$backup_fullpath/worlds/$mc_world_name" --output="$www_dir/nether" \
+		--zoomout=4 --zoomin=4 --dimension nether --background="#000000" --topY 92 --gndxray -f --log-level="warning" &
+	pid_list="$pid_list $!"
+
+	echo "Generating nether map [lower slice]..."
+	"$unmined_dir/unmined-cli" web render --world="$backup_fullpath/worlds/$mc_world_name" --output="$www_dir/nether_lower" \
+		--zoomout=4 --zoomin=4 --dimension nether --background="#000000" --topY 70 --gndxray -f --log-level="warning" &
+	pid_list="$pid_list $!"
+
+	echo "Waiting for map generation sub-processes to return..."
+	for pid in $pid_list; do
+		wait $pid || let "max_err=1"
+	done
+
+	if [ $max_err -eq 1 ]; then
+		echo "An error occured while generating maps. Exiting."
 		exit 1
 	fi
 }
